version: "2.4"

networks:
  traefik_web:
    external:
      name: traefik_web

services:
  pipelineguiweb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pipelinegui
    ports:
      - 8096:8080
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_web"
      - "traefik.port=8096"
      - "traefik.http.routers.pipelineguiweb.rule=Host(`${TRAEFIK_FRONTEND_URL?You need to specify env TRAEFIK_FRONTEND_URL, e.g. TRAEFIK_FRONTEND_URL=name.my-domain.com}`)"
      - "traefik.http.routers.pipelineguiweb.entrypoints=websecure"
      - "traefik.http.routers.pipelineguiweb.tls.certresolver=myresolver"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_HOSTNAME=${DB_HOSTNAME}

    networks:
      - traefik_web
    volumes:
      - .:/app
      - ../kube_config/:/kube
      - /share/data2/cellprofiler/automation/:/cpp_work # mount the work and result nfs share from the fs of the dev node
